language: r
cache: packages
dist: xenial
addons:
  apt:
    packages:
      - libnode-dev
r_packages:
  - covr
r_packages_github:
  - ropensci/jsonvalidate
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
